########################################################################################
#                                                                                      #
#      WAVIN AHC-9000 FLOOR HEATING CONTROLLER SOFTWARE FOR HOME ASSISTANT             #
#                                                                                      #   
#        Code developed by : Heine Koldbro Madsen and Samuel Sieb 2021                 #
#                                                                                      #
#           https://github.com/heinekmadsen/esphome_wavinahc9000v3/tree/main           #    
#                                                                                      #
# Hardware by : Mogens Groth Nicolaisen https://github.com/nic6911/Wavin-AHC-9000-mqtt #
#                                                                                      #
########################################################################################
 
esphome:
  name: wavin
  friendly_name: Wavin

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

external_components:
  - source: github://heinekmadsen/esphome_components
    components: [wavinahc9000v3]
    refresh: 0s

logger:
  baud_rate: 0  # Disable UART logging

uart:
  id: uart_wavin
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 38400
  stop_bits: 1
  parity: NONE

wavinahc9000v3:
  id: wavin
  uart_id: uart_wavin
  flow_control_pin: GPIO3
  update_interval: 10s
  allow_mode_writes: false
  poll_channels_per_cycle: 1

  channel_01_friendly_name: "Soveværelse"
  #channel_02_friendly_name: "Kontor"
  channel_03_friendly_name: "Stue 1"
  #channel_04_friendly_name: "Stue 2"

climate:
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "Soveværelse"
    channel: 1
  # - platform: wavinahc9000v3
  #   wavinahc9000v3_id: wavin
  #   name: "Kontor"
  #   channel: 2
  #   use_floor_temperature: true
  #   strict_mode_writes: true
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "Stue"
    members: [3, 4]

sensor:
  # Ch.1 Soveværelse
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "Soveværelse Batteri"
    channel: 1
    type: battery
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "Soveværelse Temperatur"
    channel: 1
    type: temperature
  # # Ch.2 Kontor
  # - platform: wavinahc9000v3
  #   wavinahc9000v3_id: wavin
  #   name: "Kontor Batteri"
  #   channel: 2
  #   type: battery
  # - platform: wavinahc9000v3
  #   wavinahc9000v3_id: wavin
  #   name: "Kontor Temperatur"
  #   channel: 2
  #   type: temperature
  # - platform: wavinahc9000v3
  #   wavinahc9000v3_id: wavin
  #   name: "Kontor Komfort Setpunkt"
  #   channel: 2
  #   type: comfort_setpoint
  # - platform: wavinahc9000v3
  #   wavinahc9000v3_id: wavin
  #   name: "Kontor Gulvtemperatur"
  #   channel: 2
  #   type: floor_temperature
  # - platform: wavinahc9000v3
  #   wavinahc9000v3_id: wavin
  #   name: "Kontor Gulv Minimum"
  #   channel: 2
  #   type: floor_min_temperature
  # - platform: wavinahc9000v3
  #   wavinahc9000v3_id: wavin
  #   name: "Kontor Gulv Maksimum"
  #   channel: 2
  #   type: floor_max_temperature
  # Ch.3/4 Stue zone
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "Stue Temperatur"
    channel: 3
    type: temperature
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "Stue Batteri"
    channel: 3
    type: battery

switch:
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "Soveværelse Børnelås"
    channel: 1
    type: child_lock
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "Stue Børnelås"
    channel: 3
    type: child_lock


api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wavin Fallback Hotspot"
    password: ""

ota:
  platform: esphome

