type: vertical-stack
cards:
  - entity: climate.nilan_genvex
    name: Nilan Ventilation
    sensors:
      - entity: sensor.nilan_luftfugtighed
        name: Luftfugtighed
    step_size: 1
    type: 'custom:simple-thermostat'
  - elements:
      - entity: sensor.nilan_udendors_temp
        style:
          color: white
          font-size: 150%
          left: 30.5%
          top: 9.0%
        type: state-label
      - entity: sensor.nilan_afkast_temp
        style:
          color: white
          font-size: 150%
          left: 71.5%
          top: 9.0%
        type: state-label
      - entity: sensor.nilan_udsug_temp
        style:
          color: white
          font-size: 150%
          left: 30.5%
          top: 65.2%
        type: state-label
      - entity: sensor.nilan_indblaes_temp
        style:
          color: white
          font-size: 150%
          left: 71.5%
          top: 65.2%
        type: state-label
      - entity: sensor.nilan_luftfugtighed
        style:
          color: white
          font-size: 150%
          left: 51.0%
          top: 77.2%
        type: state-label
    image: /local/ventilation.png
    type: picture-elements
  - type: grid
    cards:
      - type: gauge
        entity: sensor.sonoff_nilan_energy_current
        min: 0
        name: Ampere
        severity:
          green: 0
          yellow: 1
          red: 3
        max: 3
      - type: gauge
        min: 0
        max: 240
        entity: sensor.sonoff_nilan_energy_voltage
        name: Volt
      - type: gauge
        min: 0
        max: 100
        entity: sensor.sonoff_nilan_energy_power
        name: Watt
        severity:
          green: 50
          yellow: 100
          red: 180
  - type: entities
    entities:
      - type: 'custom:fold-entity-row'
        head:
          type: section
          label: Information
        entities:
          - entity: binary_sensor.nilan_controller
            state_color: true
          - entity: binary_sensor.nilan_modbus_sensor
            state_color: true
            name: Modbus Forbindelse
          - entity: binary_sensor.brugervalg_status
            state_color: true
            name: Brugervalg aktiv
          - entity: binary_sensor.nilan_bypass
            state_color: true
          - entity: sensor.nilan_model
          - entity: sensor.drift
          - entity: sensor.nilan_filterstatus
            state_color: true
          - entity: sensor.nilan_udblaes_procent
          - entity: sensor.nilan_indblaes_procent
          - entity: fan.nilan
  - type: entities
    entities:
      - type: 'custom:fold-entity-row'
        head:
          type: section
          label: Brugervalg
        entities:
          - input_select.weekprogram_mode
          - input_select.brugervalg_mode
          - input_select.usertime_mode
          - entity: input_number.user_vent
            name: Bl√¶ser indstilling
          - entity: input_number.user_temp
            name: Temperatur
          - entity: switch.nilan_bruger_valg
            name: Aktiver Brugervalg

