esphome:
  name: duplexvent
esp32:
  board: pico32
  framework:
    type: arduino


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Duplexvent Fallback Hotspot"
    password: "12345678"

captive_portal:

uart:
  rx_pin: 13
  tx_pin: 14
  parity: NONE
  baud_rate: 9600
  id: uart_modbus
  stop_bits: 1
  
modbus:
  id: modbus_id
  flow_control_pin: 26
  uart_id: uart_modbus
  
modbus_controller:
  id: duplexvent_modbus_controller
  address: 1
  modbus_id: modbus_id
  update_interval: 10s
 
external_components:
  - source: github://Jopand/esphome_components@develop
    refresh: 0s
    
nilan:
    
select:
      
  - platform: modbus_controller
    modbus_controller_id: duplexvent_modbus_controller
    name: "Set operation mode"
    id: duplex_set_operation_mode
    address: 100
    force_new_range: true
    use_write_multiple: true
    optionsmap:
      "Standard" : 0
      "VOD" : 1


sensor:

###########################
#### HOLDING REGISTERS ####
###########################


  - platform: modbus_controller
    modbus_controller_id: duplexvent_modbus_controller
    name: "Return temperature"
    id: duplex_return_temp
    unit_of_measurement: 째C
    accuracy_decimals: 1
    device_class: temperature
    register_type: holding
    address: 20
    filters:
      - multiply: 0.1
      
  - platform: modbus_controller
    modbus_controller_id: duplexvent_modbus_controller
    name: "Supply temperature"
    id: duplex_supply_temp
    unit_of_measurement: 째C
    accuracy_decimals: 1
    device_class: temperature    
    register_type: holding
    address: 21
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: duplexvent_modbus_controller
    name: "Alarm code"
    id: duplex_alarm_code  
    register_type: holding
    address: 2

  # - platform: modbus_controller
  #   modbus_controller_id: duplexvent_modbus_controller
  #   name: "Supply temperature"
  #   id: duplex_supply_temp
  #   unit_of_measurement: 째C
  #   accuracy_decimals: 1
  #   device_class: temperature
  #   register_type: holding
  #   address: 22
  #   filters:
  #     - multiply: 0.1
      
  # - platform: modbus_controller
  #   modbus_controller_id: duplexvent_modbus_controller
  #   name: "Panel temperature"
  #   id: duplex_panel_temp
  #   unit_of_measurement: 째C
  #   accuracy_decimals: 1
  #   device_class: temperature
  #   register_type: holding
  #   address: 23
  #   filters:
  #     - multiply: 0.1

  # - platform: modbus_controller
  #   modbus_controller_id: duplexvent_modbus_controller
  #   name: "Humidity"
  #   id: duplex_humidity
  #   unit_of_measurement: '%'
  #   accuracy_decimals: 1
  #   device_class: humidity
  #   register_type: holding
  #   address: 29
  #   filters:
  #     - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: duplexvent_modbus_controller
    name: "Exhaust fan speed"
    id: duplex_exhaust_fan_speed
    unit_of_measurement: '%'
    icon: "mdi:percent"
    accuracy_decimals: 1
    register_type: holding
    address: 6
    filters:
      - multiply: 1  
    
  - platform: modbus_controller
    modbus_controller_id: duplexvent_modbus_controller
    name: "Inlet fan speed"
    id: duplex_inlet_fan_speed
    unit_of_measurement: '%'
    icon: "mdi:percent"
    accuracy_decimals: 1
    register_type: holding
    address: 5
    filters:
      - multiply: 1   
          
number:
    
  - platform: modbus_controller
    modbus_controller_id: duplexvent_modbus_controller
    name: "Ventilation speed set"
    id: duplex_ventilation_speed_set
    register_type: holding
    min_value: 0
    max_value: 3
    step: 1.0
    address: 101
    #force_new_range: true
    #use_write_multiple: true  

  - platform: modbus_controller
    modbus_controller_id: duplexvent_modbus_controller
    name: "Temperature set"
    id: duplex_target_temperature_set
    register_type: holding
    min_value: 18
    max_value: 28
    step: 1.0
    address: 128
    #force_new_range: true
    #use_write_multiple: true
    multiply: 1

switch:
  - platform: modbus_controller
    modbus_controller_id: duplexvent_modbus_controller
    name: "On/Off state"
    id: duplex_on_off_state
    register_type: holding
    bitmask: 1
    #force_new_range: true
    #use_write_multiple: true
    address: 1    

    
climate:
  - platform: nilan
    name: Duplexvent
    current_temp_sensor_id: duplex_supply_temp
    target_temp_sensor_id: duplex_target_temperature_set
    fan_speed_sensor_id: duplex_ventilation_speed_set
    mode_select_id: duplex_set_operation_mode
    